ingress:
  hosts:
    - host:
      paths:
        - path: /adminer
          pathType: Prefix
          backend:  
            serviceName: adminer
            servicePort: 8080
    - host:
      paths: 
        - path: /api/
          pathType: Prefix
          backend:
            serviceName: kanban-app
            servicePort: 8080
        - path: /
          pathType: Prefix
          backend:
            serviceName: kanban-ui
            servicePort: 80